import { Connection, PublicKey } from '@solana/web3.js';
import * as anchor from '@coral-xyz/anchor';
import { readFileSync } from 'fs';
const A = 'cYu5RCMNDawsqqxLkGLaqZnKqNm4LguGveoARqthkcv';
const r = await fetch(`https://mempire-api-19110f59a37d.herokuapp.com/api/player/${A}`);
const j = await r.json();
console.log('saved deck len:', (j.deck||[]).length, 'slots:', (j.slots||[]).map(s=>s.length), 'slot:', j.slot);
console.log('saved cards:', (j.cards||[]).length);
console.log('sample saved card:', JSON.stringify((j.cards||[])[0]));
const conn = new Connection('https://api.devnet.solana.com','confirmed');
const idl = JSON.parse(readFileSync('../chain/target/idl/mempire.json','utf8'));
const prog = new anchor.Program(idl, new anchor.AnchorProvider(conn, { publicKey: new PublicKey(A), signTransaction: async t=>t, signAllTransactions: async t=>t }, {commitment:'confirmed'}));
const all = await prog.account.card.all();
const mine = all.filter(c=>c.account.owner.toBase58()===A);
console.log('chain cards owned:', mine.length);
console.log('chain mints:', mine.slice(0,3).map(c=>c.account.coinMint.toBase58().slice(0,8)));
console.log('saved mints :', (j.cards||[]).slice(0,3).map(c=>String(c.mint).slice(0,8)));
